name: Check Whats News Changes

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - '*' # all branches, including forks

jobs:
  check-whats-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in whats_news.rst
        run: |
          git fetch
          diff_output=$(git diff --name-only FETCH_HEAD docs/whats_news.rst)
          if [[ -n "$diff_output" ]]; then
            echo "whats_news.rst has been changed."
            # Add any additional steps you want to perform when the file has changed.
          else
            echo "whats_news.rst has not been changed."
            echo "::error::whats_news.rst has not been changed. CI will fail."
            exit 1
          fi



